### 3.2.1 从 Python 列表到 PyTorch 张量

In [33]:
a = [1.0, 2.0, 1.0]

In [34]:
a[0]

1.0

In [35]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [36]:
import torch

a = torch.ones(3)
a

tensor([1., 1., 1.])

In [37]:
a[1]

tensor(1.)

In [38]:
float(a[1])

1.0

In [39]:
a[2] = 2.0
a

tensor([1., 1., 2.])

### 3.2.3 张量的本质

In [40]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [41]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [42]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [43]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [44]:
points.shape

torch.Size([3, 2])

In [45]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [46]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [47]:
points[0, 1]

tensor(1.)

In [48]:
points[0]

tensor([4., 1.])

## 3.3 索引张量

In [49]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [50]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [51]:
points[1:, 0]

tensor([5., 2.])

In [52]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

## 3.4 命名张量

In [53]:
img_t = torch.randn(3, 5, 5)
img_t

tensor([[[-1.5405, -0.8635, -0.8780,  1.1333,  1.2353],
         [ 0.5900, -0.5115, -1.0327, -0.2437, -0.2828],
         [-0.7858,  0.8200,  0.0332, -0.3024,  0.2668],
         [ 1.0759,  1.3555, -0.3769,  0.4304, -1.1345],
         [ 0.3911,  0.0601, -1.2359,  0.1458, -0.5775]],

        [[-0.3361, -0.5447, -0.6013,  0.9648, -0.8102],
         [ 0.0058,  0.0847, -0.8399, -0.6305,  1.4760],
         [-0.0533, -0.6654,  0.5107,  1.6108, -0.0636],
         [-0.0843,  0.2961,  0.4292, -0.0403,  0.5910],
         [ 0.5189, -0.0557, -1.1104, -1.6029, -0.1218]],

        [[-0.6936,  0.6164,  0.3463,  0.0081, -0.3586],
         [-0.7756, -0.4723, -0.3524,  0.5900,  0.2108],
         [ 0.1701, -1.0131, -0.9605, -0.1174,  1.4315],
         [ 0.4463,  1.2121,  0.1126,  1.8416,  0.7648],
         [ 0.4149, -0.1476, -0.6983, -0.0743,  1.3411]]])

In [54]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])
weights

tensor([0.2126, 0.7152, 0.0722])

In [55]:
batch_t = torch.randn(2, 3, 5, 5)
batch_t

tensor([[[[-0.5542,  2.3576,  0.1943,  1.5308,  1.1323],
          [ 0.9105,  0.5439, -0.4888, -0.4740, -0.2012],
          [-1.0308, -1.8053,  1.2525, -0.2673, -0.8321],
          [ 1.1008,  0.9821,  0.5802, -0.7527,  0.5258],
          [ 1.2370, -0.9986,  0.2618, -0.5788,  0.8815]],

         [[-0.7740,  0.5592, -0.6151,  1.4602,  0.2703],
          [ 0.4741, -0.4367, -0.9186, -2.4352,  0.6936],
          [-0.3328,  0.3677,  0.5530, -1.3658, -0.1727],
          [-0.5503,  0.5740,  1.1759,  1.8552,  1.9016],
          [ 2.1341,  1.7270, -0.5348,  1.0389,  1.1842]],

         [[-1.0104, -0.7795,  0.5309, -0.4245,  0.7802],
          [ 0.5191,  1.0021,  0.1250,  0.3412,  1.1504],
          [-1.4196,  0.4387, -2.5478,  1.9443,  1.5243],
          [ 1.5630, -0.5831,  1.6427, -0.7921, -1.3171],
          [ 0.5173, -0.4396, -0.7433,  0.2009,  0.5115]]],


        [[[ 2.9929,  1.6040,  1.5121, -0.0706,  0.7651],
          [-0.0126,  0.5887, -0.1644,  0.1798, -0.8035],
          [ 0.9009,  0.

In [56]:
# 沿倒数第三个维度计算平均值
img_gray_native = img_t.mean(-3)
img_gray_native

tensor([[-0.8567, -0.2639, -0.3777,  0.7021,  0.0222],
        [-0.0599, -0.2997, -0.7417, -0.0948,  0.4680],
        [-0.2230, -0.2862, -0.1388,  0.3970,  0.5449],
        [ 0.4793,  0.9546,  0.0550,  0.7439,  0.0738],
        [ 0.4417, -0.0477, -1.0148, -0.5104,  0.2140]])

In [57]:
batch_gray_native = batch_t.mean(-3)
batch_gray_native

tensor([[[-0.7795,  0.7125,  0.0367,  0.8555,  0.7276],
         [ 0.6346,  0.3697, -0.4275, -0.8560,  0.5476],
         [-0.9277, -0.3330, -0.2474,  0.1038,  0.1731],
         [ 0.7045,  0.3244,  1.1329,  0.1034,  0.3701],
         [ 1.2962,  0.0963, -0.3387,  0.2203,  0.8591]],

        [[ 0.6680,  0.2360,  0.0424,  0.6081,  0.4399],
         [-0.9687,  0.1129, -0.4681,  0.3514,  0.1911],
         [ 0.4813,  0.7930,  0.6609,  0.3733,  0.1922],
         [ 0.4164, -0.6140, -0.3754,  0.5153, -0.6244],
         [ 0.3170,  1.0178,  0.0282, -0.4036, -0.4070]]])

In [58]:
img_gray_native.shape, batch_gray_native.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [59]:
weights

tensor([0.2126, 0.7152, 0.0722])

In [62]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
unsqueezed_weights, unsqueezed_weights.shape

(tensor([[[0.2126]],
 
         [[0.7152]],
 
         [[0.0722]]]),
 torch.Size([3, 1, 1]))

In [61]:
img_weights = (img_t * unsqueezed_weights)
img_weights, img_weights.shape

(tensor([[[-3.2751e-01, -1.8358e-01, -1.8667e-01,  2.4095e-01,  2.6263e-01],
          [ 1.2543e-01, -1.0875e-01, -2.1956e-01, -5.1820e-02, -6.0124e-02],
          [-1.6707e-01,  1.7433e-01,  7.0683e-03, -6.4280e-02,  5.6712e-02],
          [ 2.2874e-01,  2.8817e-01, -8.0136e-02,  9.1503e-02, -2.4120e-01],
          [ 8.3154e-02,  1.2776e-02, -2.6275e-01,  3.1006e-02, -1.2277e-01]],
 
         [[-2.4035e-01, -3.8955e-01, -4.3002e-01,  6.9003e-01, -5.7948e-01],
          [ 4.1146e-03,  6.0586e-02, -6.0071e-01, -4.5093e-01,  1.0556e+00],
          [-3.8124e-02, -4.7591e-01,  3.6528e-01,  1.1521e+00, -4.5454e-02],
          [-6.0294e-02,  2.1174e-01,  3.0697e-01, -2.8843e-02,  4.2268e-01],
          [ 3.7115e-01, -3.9815e-02, -7.9413e-01, -1.1464e+00, -8.7097e-02]],
 
         [[-5.0080e-02,  4.4507e-02,  2.5005e-02,  5.8342e-04, -2.5893e-02],
          [-5.5995e-02, -3.4101e-02, -2.5445e-02,  4.2595e-02,  1.5217e-02],
          [ 1.2283e-02, -7.3146e-02, -6.9350e-02, -8.4767e-03,  1.0336

In [63]:
batch_weights = (batch_t * unsqueezed_weights)
batch_weights

tensor([[[[-0.1178,  0.5012,  0.0413,  0.3254,  0.2407],
          [ 0.1936,  0.1156, -0.1039, -0.1008, -0.0428],
          [-0.2191, -0.3838,  0.2663, -0.0568, -0.1769],
          [ 0.2340,  0.2088,  0.1234, -0.1600,  0.1118],
          [ 0.2630, -0.2123,  0.0557, -0.1231,  0.1874]],

         [[-0.5536,  0.3999, -0.4399,  1.0443,  0.1933],
          [ 0.3390, -0.3123, -0.6569, -1.7416,  0.4961],
          [-0.2380,  0.2630,  0.3955, -0.9768, -0.1235],
          [-0.3936,  0.4105,  0.8410,  1.3268,  1.3600],
          [ 1.5263,  1.2351, -0.3825,  0.7430,  0.8470]],

         [[-0.0729, -0.0563,  0.0383, -0.0306,  0.0563],
          [ 0.0375,  0.0723,  0.0090,  0.0246,  0.0831],
          [-0.1025,  0.0317, -0.1840,  0.1404,  0.1101],
          [ 0.1128, -0.0421,  0.1186, -0.0572, -0.0951],
          [ 0.0373, -0.0317, -0.0537,  0.0145,  0.0369]]],


        [[[ 0.6363,  0.3410,  0.3215, -0.0150,  0.1627],
          [-0.0027,  0.1252, -0.0349,  0.0382, -0.1708],
          [ 0.1915,  0.

In [64]:
img_gray_weighted = img_weights.sum(-3)
img_gray_weighted

tensor([[-0.6179, -0.5286, -0.5917,  0.9316, -0.3427],
        [ 0.0736, -0.0823, -0.8457, -0.4602,  1.0107],
        [-0.1929, -0.3747,  0.3030,  1.0793,  0.1146],
        [ 0.2007,  0.5874,  0.2350,  0.1956,  0.2367],
        [ 0.4843, -0.0377, -1.1073, -1.1207, -0.1130]])

In [65]:
batch_gray_weighted = batch_weights.sum(-3)
batch_gray_weighted

tensor([[[-0.7443,  0.8449, -0.3603,  1.3391,  0.4904],
         [ 0.5701, -0.1244, -0.7518, -1.8178,  0.5363],
         [-0.5597, -0.0891,  0.4779, -0.8932, -0.1904],
         [-0.0467,  0.5772,  1.0830,  1.1096,  1.3767],
         [ 1.8267,  0.9911, -0.3805,  0.6345,  1.0713]],

        [[ 0.3716,  0.2211, -0.8118,  0.6556,  1.7229],
         [-0.6823,  0.1286,  0.6292, -0.2378,  1.6662],
         [ 0.8472,  0.6074,  1.0305,  0.2567, -0.0151],
         [ 0.8432, -1.3489, -0.4587, -0.6138, -0.7328],
         [ 0.8673,  1.1532,  0.1067, -0.5876, -0.5298]]])

In [66]:
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [67]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

C:\Users\dingy\AppData\Local\Temp\ipykernel_10176\2371314847.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at C:\cb\pytorch_1000000000000\work\c10/core/TensorImpl.h:1761.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

### 3.5.2 适合任何场合的 dtype
32 位浮点数

In [71]:
torch.tensor(1.0).dtype

torch.float32

## 3.6 张量的 API

In [73]:
# 转置
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a, a_t, a.shape, a_t.shape

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.Size([3, 2]),
 torch.Size([2, 3]))

## 3.7 张量的存储视图

### 3.7.1 索引存储区

In [74]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

### 3.8.1 另一个张量的存储视图

In [75]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point

tensor([5., 3.])

In [77]:
second_point.storage_offset()

2

In [78]:
second_point.size()

torch.Size([2])

In [80]:
second_point.shape

torch.Size([2])

In [81]:
points.stride()

(2, 1)