### 3.2.1 从 Python 列表到 PyTorch 张量

In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [4]:
import torch

a = torch.ones(3)
a

tensor([1., 1., 1.])

In [5]:
a[1]

tensor(1.)

In [6]:
float(a[1])

1.0

In [7]:
a[2] = 2.0
a

tensor([1., 1., 2.])

### 3.2.3 张量的本质

In [8]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [10]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [11]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
points.shape

torch.Size([3, 2])

In [13]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [14]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
points[0, 1]

tensor(1.)

In [16]:
points[0]

tensor([4., 1.])

## 3.3 索引张量

In [17]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [18]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [19]:
points[1:, 0]

tensor([5., 2.])

In [20]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

## 3.4 命名张量

In [21]:
img_t = torch.randn(3, 5, 5)
img_t

tensor([[[ 4.8440e-01,  8.8198e-01,  2.7926e-01,  1.4559e+00,  6.8543e-03],
         [-3.1018e-01,  1.0222e+00,  2.9939e-01, -1.1412e+00,  1.2415e+00],
         [ 1.0753e+00,  1.5666e+00,  1.5215e+00,  5.7134e-01,  1.5227e+00],
         [ 7.2092e-02, -3.5374e-01, -1.1719e+00, -1.3437e+00, -4.0863e-01],
         [ 2.6376e+00, -3.7575e-01,  9.8120e-02,  3.5356e-01, -6.9156e-01]],

        [[ 4.5009e-02,  5.3280e-01, -1.5943e+00,  1.0826e+00,  2.3970e+00],
         [ 4.6953e-01,  5.7612e-01,  3.9899e-01, -4.8787e-01,  1.2667e-01],
         [ 1.0613e+00,  5.0753e-01, -1.6200e-01, -1.1259e+00,  2.2169e-01],
         [-1.2203e+00,  6.0524e-01, -1.2988e+00,  1.4768e+00,  2.4918e-01],
         [-6.0506e-01, -1.2308e+00, -8.6764e-01,  8.7060e-02,  1.6631e+00]],

        [[-1.1143e+00,  1.3926e+00, -2.1637e+00, -1.5026e-03, -1.2554e+00],
         [ 1.3642e+00,  5.0821e-01,  5.3825e-02,  1.1947e+00,  1.7433e-01],
         [-5.0468e-01,  3.4789e-01,  3.1970e-01, -1.0256e-01,  1.0842e+00],
        

In [22]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])
weights

tensor([0.2126, 0.7152, 0.0722])

In [23]:
batch_t = torch.randn(2, 3, 5, 5)
batch_t

tensor([[[[-0.1089,  0.0500,  0.4507, -0.9297,  0.3050],
          [-0.2154,  0.2455, -1.8465, -0.5148, -0.3447],
          [ 0.5459, -0.1138,  0.6568,  0.8274, -0.4142],
          [ 0.7161, -0.3949, -0.2938,  1.5770, -0.1347],
          [ 0.2745,  0.1481,  1.6340,  1.2752, -0.7677]],

         [[ 0.2713,  1.3213,  1.2670,  0.3995,  0.1726],
          [-0.3849, -0.3180,  0.4133, -0.0901,  1.2889],
          [-1.0583,  2.1563,  1.0159,  2.0020, -0.5686],
          [-1.2199, -0.4464,  1.2580, -1.1466, -1.0876],
          [-0.1226,  0.6539,  1.7329,  0.3559, -0.0839]],

         [[-0.7459,  2.2489,  0.2931, -0.9879,  0.1461],
          [ 0.9545, -2.5840, -0.2718, -0.6872,  0.2812],
          [-0.0907, -0.4865,  0.6384, -0.5080,  1.3905],
          [-0.8127,  0.3222, -0.0633,  0.8922, -0.6999],
          [-0.8663, -0.3978, -1.1409, -0.9002, -1.5194]]],


        [[[ 0.1229,  1.1436,  1.1538,  1.9187, -0.7145],
          [-0.7262, -0.1961,  1.9447, -2.7476,  0.5643],
          [ 0.1909, -1.

In [24]:
# 沿倒数第三个维度计算平均值
img_gray_native = img_t.mean(-3)
img_gray_native

tensor([[-0.1950,  0.9358, -1.1596,  0.8457,  0.3828],
        [ 0.5079,  0.7022,  0.2507, -0.1448,  0.5142],
        [ 0.5440,  0.8074,  0.5597, -0.2190,  0.9429],
        [-0.7008,  0.0059, -1.3397,  0.1937,  0.4250],
        [ 0.1647, -0.2387,  0.0627,  0.3474, -0.0312]])

In [25]:
batch_gray_native = batch_t.mean(-3)
batch_gray_native

tensor([[[-0.1945,  1.2067,  0.6703, -0.5060,  0.2079],
         [ 0.1181, -0.8855, -0.5683, -0.4307,  0.4085],
         [-0.2010,  0.5187,  0.7704,  0.7738,  0.1359],
         [-0.4389, -0.1730,  0.3003,  0.4409, -0.6407],
         [-0.2382,  0.1347,  0.7420,  0.2436, -0.7904]],

        [[-0.5232,  0.6486,  0.5193,  1.2558, -0.6714],
         [-0.3182,  0.1284,  0.6328, -0.5218,  0.6218],
         [ 0.4581, -0.7381, -0.3554,  1.1665,  0.5846],
         [ 0.7406,  0.1097, -1.4558,  0.3138, -0.6831],
         [ 0.6682, -0.8859, -0.0631, -0.3678, -0.0619]]])

In [26]:
img_gray_native.shape, batch_gray_native.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [27]:
weights

tensor([0.2126, 0.7152, 0.0722])

In [28]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
unsqueezed_weights, unsqueezed_weights.shape

(tensor([[[0.2126]],
 
         [[0.7152]],
 
         [[0.0722]]]),
 torch.Size([3, 1, 1]))

In [29]:
img_weights = (img_t * unsqueezed_weights)
img_weights, img_weights.shape

(tensor([[[ 1.0298e-01,  1.8751e-01,  5.9371e-02,  3.0953e-01,  1.4572e-03],
          [-6.5945e-02,  2.1733e-01,  6.3650e-02, -2.4262e-01,  2.6394e-01],
          [ 2.2861e-01,  3.3307e-01,  3.2347e-01,  1.2147e-01,  3.2373e-01],
          [ 1.5327e-02, -7.5204e-02, -2.4916e-01, -2.8567e-01, -8.6876e-02],
          [ 5.6076e-01, -7.9885e-02,  2.0860e-02,  7.5167e-02, -1.4703e-01]],
 
         [[ 3.2190e-02,  3.8106e-01, -1.1402e+00,  7.7426e-01,  1.7143e+00],
          [ 3.3581e-01,  4.1204e-01,  2.8536e-01, -3.4892e-01,  9.0594e-02],
          [ 7.5905e-01,  3.6299e-01, -1.1586e-01, -8.0522e-01,  1.5855e-01],
          [-8.7274e-01,  4.3287e-01, -9.2891e-01,  1.0562e+00,  1.7822e-01],
          [-4.3274e-01, -8.8028e-01, -6.2054e-01,  6.2266e-02,  1.1894e+00]],
 
         [[-8.0454e-02,  1.0055e-01, -1.5622e-01, -1.0849e-04, -9.0637e-02],
          [ 9.8497e-02,  3.6693e-02,  3.8862e-03,  8.6255e-02,  1.2587e-02],
          [-3.6438e-02,  2.5118e-02,  2.3083e-02, -7.4049e-03,  7.8280

In [30]:
batch_weights = (batch_t * unsqueezed_weights)
batch_weights

tensor([[[[-0.0232,  0.0106,  0.0958, -0.1976,  0.0648],
          [-0.0458,  0.0522, -0.3926, -0.1095, -0.0733],
          [ 0.1161, -0.0242,  0.1396,  0.1759, -0.0881],
          [ 0.1522, -0.0840, -0.0625,  0.3353, -0.0286],
          [ 0.0584,  0.0315,  0.3474,  0.2711, -0.1632]],

         [[ 0.1941,  0.9450,  0.9062,  0.2857,  0.1235],
          [-0.2753, -0.2274,  0.2956, -0.0644,  0.9218],
          [-0.7569,  1.5422,  0.7266,  1.4318, -0.4067],
          [-0.8725, -0.3193,  0.8997, -0.8200, -0.7779],
          [-0.0877,  0.4676,  1.2394,  0.2546, -0.0600]],

         [[-0.0539,  0.1624,  0.0212, -0.0713,  0.0105],
          [ 0.0689, -0.1866, -0.0196, -0.0496,  0.0203],
          [-0.0065, -0.0351,  0.0461, -0.0367,  0.1004],
          [-0.0587,  0.0233, -0.0046,  0.0644, -0.0505],
          [-0.0626, -0.0287, -0.0824, -0.0650, -0.1097]]],


        [[[ 0.0261,  0.2431,  0.2453,  0.4079, -0.1519],
          [-0.1544, -0.0417,  0.4135, -0.5841,  0.1200],
          [ 0.0406, -0.

In [31]:
img_gray_weighted = img_weights.sum(-3)
img_gray_weighted

tensor([[ 0.0547,  0.6691, -1.2371,  1.0837,  1.6251],
        [ 0.3684,  0.6661,  0.3529, -0.5053,  0.3671],
        [ 0.9512,  0.7212,  0.2307, -0.6912,  0.5606],
        [-0.9263,  0.3408, -1.2899,  0.8029,  0.1949],
        [ 0.0170, -0.8959, -0.5305,  0.1809,  0.9655]])

In [32]:
batch_gray_weighted = batch_weights.sum(-3)
batch_gray_weighted

tensor([[[ 0.1170,  1.1180,  1.0232,  0.0168,  0.1989],
         [-0.2521, -0.3618, -0.1166, -0.2235,  0.8689],
         [-0.6474,  1.4829,  0.9123,  1.5710, -0.3943],
         [-0.7789, -0.3800,  0.8327, -0.4203, -0.8570],
         [-0.0919,  0.4704,  1.5044,  0.4607, -0.3329]],

        [[-0.0401,  0.4823,  0.9720,  0.9104, -0.6672],
         [ 0.0814, -0.4602,  0.2757, -0.8417,  0.7538],
         [ 0.6990, -0.9171, -0.0141,  1.1064,  0.9115],
         [ 0.8106, -1.0489, -1.2255,  1.1590, -0.2463],
         [ 0.0845, -0.7802, -0.3373, -0.8509,  0.9101]]])

In [33]:
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [34]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

C:\Users\dingy\AppData\Local\Temp\ipykernel_10036\2338252810.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at C:\cb\pytorch_1000000000000\work\c10/core/TensorImpl.h:1761.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

### 3.5.2 适合任何场合的dtype
32 位浮点数

In [35]:
torch.tensor(1.0).dtype

torch.float32

## 3.6 张量的 API

In [36]:
# 转置
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a, a_t, a.shape, a_t.shape

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 torch.Size([3, 2]),
 torch.Size([2, 3]))

## 3.7 张量的存储视图

### 3.7.1 索引存储区

In [37]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

### 3.8.1 另一个张量的存储视图

In [38]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point

tensor([5., 3.])

In [39]:
second_point.storage_offset()

2

In [40]:
second_point.size()

torch.Size([2])

In [41]:
second_point.shape

torch.Size([2])

In [42]:
points.stride()

(2, 1)

In [43]:
second_point = points[1]
second_point, second_point.size()

(tensor([5., 3.]), torch.Size([2]))

In [44]:
second_point.storage_offset()

2

In [45]:
second_point.stride()

(1,)

In [47]:
# 更改子张量会对原始张量产生影响
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [48]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

### 3.8.2 无复制转置

In [49]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [50]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [51]:
id(points.storage()) == id(points_t.storage())

True

In [52]:
points.stride(), points_t.stride()

((2, 1), (1, 2))

### 3.8.3 高维转置

In [53]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [54]:
transpose_t.shape

torch.Size([5, 4, 3])

In [55]:
some_t.stride(), transpose_t.stride()

((20, 5, 1), (1, 5, 20))

### 3.8.4 连续张量

In [56]:
points.is_contiguous(), points_t.is_contiguous()

(True, False)

In [57]:
points_t_cont = points_t.contiguous()
id(points_t_cont) == id(points)

False

## 3.9 将张量存储到 GPU

In [58]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [59]:
points_gpu = points.to(device='cuda')
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [60]:
points_cpu = points_gpu.to(device='cpu')

In [61]:
points_gpu = points.cuda()
points_cpu = points.cpu()
points_cpu, points_gpu

(tensor([[4., 1.],
         [5., 3.],
         [2., 1.]]),
 tensor([[4., 1.],
         [5., 3.],
         [2., 1.]], device='cuda:0'))

In [62]:
id(points_cpu), id(points_gpu)

(2257844964064, 2257845388208)

## 3.10 NumPy 互操作性

In [63]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [64]:
points = torch.from_numpy(points_np)
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## 3.12 序列化张量