In [59]:
### 4.1.2 加载图像文件

In [60]:
import imageio.v2 as imageio

In [61]:
img_arr = imageio.imread('./data/p1ch4/image-dog/bobby.jpg')
img_arr.shape

(720, 1280, 3)

### 4.1.3 改变布局

In [62]:
import torch

img = torch.from_numpy(img_arr)
out = img.permute(2, 0, 1)

In [63]:
batch_size = 3
batch = torch.zeros(batch_size, 3, 256, 256, dtype=torch.uint8)
batch.shape

torch.Size([3, 3, 256, 256])

In [64]:
import os

In [65]:
data_dir = "./data/p1ch4/image-cats"
filenames = [name for name in os.listdir(data_dir) if os.path.splitext(name)[-1] == ".png"]
filenames

['cat1.png', 'cat2.png', 'cat3.png']

In [66]:
for i, filename in enumerate(filenames):
    img_arr = imageio.imread(os.path.join(data_dir, filename))
    img_t = torch.from_numpy(img_arr)
    img_t = img_t.permute(2, 0, 1)
    img_t = img_t[:3]
    batch = img_t
batch

tensor([[[238, 238, 238,  ..., 214, 215, 215],
         [238, 238, 238,  ..., 214, 215, 215],
         [238, 238, 238,  ..., 214, 215, 215],
         ...,
         [214, 213, 212,  ..., 187, 190, 193],
         [214, 213, 212,  ..., 186, 190, 192],
         [214, 213, 212,  ..., 186, 190, 192]],

        [[195, 195, 195,  ..., 173, 175, 175],
         [195, 195, 195,  ..., 173, 175, 175],
         [195, 195, 195,  ..., 173, 175, 175],
         ...,
         [128, 127, 126,  ..., 100, 103, 106],
         [128, 127, 126,  ...,  99, 103, 105],
         [128, 127, 126,  ...,  99, 103, 105]],

        [[137, 137, 137,  ..., 125, 126, 126],
         [137, 137, 137,  ..., 125, 126, 126],
         [137, 137, 137,  ..., 125, 126, 126],
         ...,
         [ 79,  78,  77,  ...,  64,  68,  72],
         [ 79,  78,  77,  ...,  64,  69,  71],
         [ 79,  78,  77,  ...,  65,  69,  72]]], dtype=torch.uint8)

## 4.2 三维图像：体数据

In [67]:
dir_path = "../PyTorch深度学习实战/data/p1ch4/volumetric-dicom/2-LUNG 3.0  B70f-04083"
vol_arr = imageio.volread(dir_path, 'DICOM')
vol_arr.shape

Reading DICOM (examining files): 99/99 files (100.0%)
  Found 1 correct series.
Reading DICOM (loading data): 99/99  (100.0%)


(99, 512, 512)

In [68]:
vol = torch.from_numpy(vol_arr).float()
vol = torch.unsqueeze(vol, 0)

vol.shape

torch.Size([1, 99, 512, 512])

## 4.3 表示表格数据

In [69]:
import csv
import numpy as np

In [70]:
wine_path = "./data/p1ch4/tabular-wine/winequality-white.csv"
wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=";", skiprows=1)
wineq_numpy

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [71]:
col_list = next(csv.reader(open(wine_path), delimiter=';'))

wineq_numpy.shape, col_list

((4898, 12),
 ['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol',
  'quality'])

In [72]:
wineq = torch.from_numpy(wineq_numpy)
wineq.shape, wineq.dtype

(torch.Size([4898, 12]), torch.float32)

In [73]:
data = wineq[:, :-1]
data, data.shape

(tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
         [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
         [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
         ...,
         [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
         [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
         [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]]),
 torch.Size([4898, 11]))

In [74]:
target = wineq[:, -1]
target, target.shape

(tensor([6., 6., 6.,  ..., 6., 7., 6.]), torch.Size([4898]))

In [75]:
target = wineq[:, -1].long()
target

tensor([6, 6, 6,  ..., 6, 7, 6])

In [76]:
target_onehot = torch.zeros(target.shape[0], 10)
target_onehot, target_onehot.shape

(tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]),
 torch.Size([4898, 10]))

In [78]:
indices = torch.tensor(list(range(5))).view(5, 1)
indices, indices.shape

(tensor([[0],
         [1],
         [2],
         [3],
         [4]]),
 torch.Size([5, 1]))

In [79]:
result = torch.zeros(5, 5)
result

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [80]:
result.scatter_(1, indices, 1)
result

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [81]:
target_onehot.scatter_(1, target.unsqueeze(1), 1.0)
target_onehot, target_onehot.shape

(tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 1., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]),
 torch.Size([4898, 10]))

### 4.3.5 何时分类